class dataclass:
	FIGURE_LAST_ID = 0
	SCHEME_TEXT_TYPE = 2
	BLOCK_TYPE = 1

	CONNECTION_HIER_TYPE = 'H'
	CONNECTION_KINDS_TYPE = 'K'
	CONNECTION_NUM_ORDER_TYPE = 'N'

	TEXT_INTER_TYPE = 'BT'
	COMBO_INTER_TYPE = 'CT'
	TOGGLE_INTER_TYPE = 'TT'