# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design/uploadDataDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uploadMapInfoDialog(object):
    def setupUi(self, uploadMapInfoDialog):
        uploadMapInfoDialog.setObjectName("uploadMapInfoDialog")
        uploadMapInfoDialog.resize(570, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(uploadMapInfoDialog.sizePolicy().hasHeightForWidth())
        uploadMapInfoDialog.setSizePolicy(sizePolicy)
        uploadMapInfoDialog.setMinimumSize(QtCore.QSize(570, 300))
        uploadMapInfoDialog.setMaximumSize(QtCore.QSize(570, 300))
        self.gridLayoutWidget = QtWidgets.QWidget(uploadMapInfoDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 571, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.okButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 6, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.nicknameLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.nicknameLineEdit.setObjectName("nicknameLineEdit")
        self.gridLayout.addWidget(self.nicknameLineEdit, 2, 0, 1, 1)
        self.adminPassLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.adminPassLineEdit.setObjectName("adminPassLineEdit")
        self.gridLayout.addWidget(self.adminPassLineEdit, 4, 0, 1, 1)
        self.userPassLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.userPassLineEdit.setObjectName("userPassLineEdit")
        self.gridLayout.addWidget(self.userPassLineEdit, 3, 0, 1, 1)
        self.mapTitleLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.mapTitleLineEdit.setObjectName("mapTitleLineEdit")
        self.gridLayout.addWidget(self.mapTitleLineEdit, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(uploadMapInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(uploadMapInfoDialog)

    def retranslateUi(self, uploadMapInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        uploadMapInfoDialog.setWindowTitle(_translate("uploadMapInfoDialog", "Enter some additional data"))
        self.okButton.setText(_translate("uploadMapInfoDialog", "OK"))
        self.nicknameLineEdit.setPlaceholderText(_translate("uploadMapInfoDialog", "Ваш никнейм"))
        self.adminPassLineEdit.setPlaceholderText(_translate("uploadMapInfoDialog", "Админский пароль (смотреть значения интерактивок)"))
        self.userPassLineEdit.setPlaceholderText(_translate("uploadMapInfoDialog", "Пароль пользователя (смотреть, скачивать, форкать)"))
        self.mapTitleLineEdit.setPlaceholderText(_translate("uploadMapInfoDialog", "Название"))
        self.label.setText(_translate("uploadMapInfoDialog", "Введите информацию о карте"))
